### ISSUE TITLE
FB7613067: Xcode cannot link a shared static library with both the Main app and its XPC service

### ISSUE THREAD

**Issue by shpakovski** [feedback-assistant/reports#89]
- **Date:** 2020-03-04
- **Resolution:** Open
- **Area:** Xcode
- **OS:** macOS 10.15.3
- **Type:** Incorrect/Unexpected Behavior
- **Keywords:** Swift PM

### What version of Xcode are you using?

Xcode Version 11.4 beta 3 (11N132i)

### Please describe the issue:

I have a Mac app with a XPC service. Both of them are linked with a static Swift library.

<img width="553" alt="image" src="https://user-images.githubusercontent.com/163410/75890140-00f18400-5e3f-11ea-9439-88c213793542.png">

This works in Xcode 11.3 but Xcode 11.4 cannot build the project and shows an error “Swift package product `StaticLibrary-Name` is linked as a static library by `MainApp-Name` and `XPCService-Name`. This will result in duplication of library code”.

### Please list the steps you took to reproduce the issue:

1. Download a sample project and extract it
1. Open the Main.xcworkspace in Xcode 11.3, build and run it with a success
1. Open the Main.xcworkspace in Xcode 11.4, build and run it with a failure 

### What did you expect to happen?

The workspace should be built and run in Xcode 11.4 like in Xcode 11.1-11.3.

### What actually happened?

The workspace cannot be built and run in Xcode 11.4.

<img width="960" alt="image" src="https://user-images.githubusercontent.com/163410/75890029-d69fc680-5e3e-11ea-8c75-2626bcec7710.png">

## File Uploads

[SharedLibrary.zip](https://github.com/feedback-assistant/reports/files/4288031/SharedLibrary.zip)

**Comment by rsalesas** [comment]
This worked for me on several projects. Xcode is not able to correctly identify that the targets are separate processes and won't have duplicate symbols.

**Comment by shpakovski** [comment]
This problem has been fixed in 11.4.1 🎉
